# To allow your IDE to autocomplete and validate your YAML pipelines, name them as <name of your choice>.haystack-pipeline.yml

version: ignore

components:    # define all the building-blocks for Pipeline
  - name: DocumentStore
    type: ElasticsearchDocumentStore
    params:
      host: localhost
      index: document
      embedding_field: question_emb
      embedding_dim: 768
      excluded_meta_data: ["question_emb"]
  - name: Retriever
    type: EmbeddingRetriever
    params:
      document_store: DocumentStore    # params can reference other components defined in the YAML
      embedding_model: deepset/sentence_bert
      top_k: 5
  - name: Doc2Answers       # custom-name for the component; helpful for visualization & debugging
    type: Docs2Answers    # Haystack Class name for the component
pipelines:
  - name: query    # a sample extractive-qa Pipeline
    nodes:
      - name: Retriever
        inputs: [Query]
      - name: Doc2Answers
        inputs: [Retriever]
