version: 1.12.2
extras: ray
components:    # define all the building-blocks for Pipeline
  - name: DocumentStore
    type: ElasticsearchDocumentStore
    params:
      host: localhost
  - name: Retriever
    type: BM25Retriever
    params:
      document_store: DocumentStore    # params can reference other components defined in the YAML
 
  - name: ImageFileConverter
    type: ImageToTextConverter
    params:
      remove_numeric_tables: false
      valid_languages:
        - chi_sim

  - name: Preprocessor
    type: PreProcessor
    params:
      split_by: word
      split_length: 500
      split_overlap: 10

pipelines:
  - name: indexing
    nodes:
      - name: ImageFileConverter
        inputs: [File]
        serve_deployment_kwargs:
            num_replicas: 60  # number of replicas to create on the Ray cluster
      - name: Preprocessor
        inputs: [ImageFileConverter]
        serve_deployment_kwargs:
            num_replicas: 10  # number of replicas to create on the Ray cluster
      - name: DocumentStore
        inputs: [Preprocessor]
        serve_deployment_kwargs:
            num_replicas: 10  # number of replicas to create on the Ray cluster
