version: 1.12.2
extras: ray
components:    # define all the building-blocks for Pipeline
  - name: DocumentStore
    type: FAISSDocumentStore
    faiss_index_path: /home/user/indexing/faiss-index-so.faiss
    actor: False
    params:
      sql_url: postgresql://postgres:postgres@localhost/haystack
      faiss_index_factory_str: HNSW

  - name: Retriever
    type: DensePassageRetriever
    actor: True
    params:
      top_k: 10
      query_embedding_model: /home/user/indexing/dpr_model_100chars_v0/query_encoder
      passage_embedding_model: /home/user/indexing/dpr_model_100chars_v0/passage_encoder
      max_seq_len_query: 128
      max_seq_len_passage: 100
      xlm_roberta: True

  - name: ImageFileConverter
    type: CustomerImageToTextConverter
    path: /home/user/indexing/image2doc_indexing/image.py
    actor: True
    params:
      remove_numeric_tables: false
      valid_languages:
        - chi_sim

  - name: Preprocessor
    type: PreProcessor
    actor: True
    params:
      split_by: word
      split_length: 200
      split_overlap: 10
  - name: Dataset
    type: Dataset
    actor: False
    params:
      path: /home/user/dataset/

pipelines:
  - name: indexing
    nodes:
      - name: Dataset
        inputs: [File]
      - name: ImageFileConverter
        inputs: [Dataset]
        serve_deployment_kwargs:
            num_replicas: 40  # number of replicas to create on the Ray cluster
            num_cpus: 2
            batch_size: 4
      
      - name: Preprocessor
        inputs: [ImageFileConverter]
        serve_deployment_kwargs:
            num_replicas: 80  # number of replicas to create on the Ray cluster
            num_cpus: 1
            batch_size: 10
      
      - name: Retriever
        inputs: [Preprocessor]
        serve_deployment_kwargs:
            num_replicas: 80  # number of replicas to create on the Ray cluster
            batch_size: 10
            num_cpus: 1
      
      - name: DocumentStore
        inputs: [Retriever]
